### ISSUE TITLE
Broken on Node 14

### ISSUE THREAD

**Issue by rafalkrupinski** [jkuri/rollup-plugin-progress#19]
Recently updated to Node 14 and my build stopped working with this error message:

```
...
(38): ${project}/node_modules/moment/moment.js?commonjs-proxy
copied:
  src/options/img → dist/options/img
(!) Plugin chrome-extension: Detected permissions: storage
[!] (plugin progress) TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (38)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (38)
    at Object.writeFileSync (fs.js:1380:5)
    at Object.generateBundle (${project}/node_modules/rollup-plugin-progress/dist/rollup-plugin-progress.js:62:10)
    at ${project}/node_modules/rollup/dist/shared/node-entry.js:13117:25
```

**Comment by favna** [comment]
Got the same although my stacktrace was a bit longer:
```
$ rollup -c rollup.config.ts
[!] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
    at Object.writeFileSync (fs.js:1380:5)
    at progress (E:\dev\favware\node_modules\rollup-plugin-progress\dist\rollup-plugin-progress.js:25:8)
    at Object.<anonymous> (E:\dev\favware\packages\querystring\rollup.config.ts:28:5)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.require.extensions.<computed> [as .ts] (E:\dev\favware\node_modules\rollup\dist\shared\loadConfigFile.js:516:20)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadConfigFromBundledFile (E:\dev\favware\node_modules\rollup\dist\shared\loadConfigFile.js:524:42)
```

**Comment by liihuu** [comment]
Same problem.
```
[!] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
    at Object.writeFileSync (fs.js:1380:5)
    at progress (/home/travis/build/liihuu/klineweb/node_modules/rollup-plugin-progress/dist/rollup-plugin-progress.js:25:8)
    at getPlugins (/home/travis/build/liihuu/klineweb/config/rollup.config.js:17:5)
    at Object.<anonymous> (/home/travis/build/liihuu/klineweb/config/rollup.config.js:49:14)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.require.extensions.<computed> [as .js] (/home/travis/build/liihuu/klineweb/node_modules/rollup/dist/shared/loadConfigFile.js:516:20)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by rafalkrupinski** [comment]
Cheers
