### ISSUE TITLE
after updating to 0.3 I get an error:

### ISSUE THREAD

**Issue by yairEO** [jkuri/rollup-plugin-progress#7]
````
[11:37:11] ReferenceError in plugin 'run-sequence(rollupPlugins)'                                  
Message:                                                                                           
    totalFilePath is not defined                                                                   
Stack:                                                                                             
ReferenceError: totalFilePath is not defined                                                       
    at progress (C:\www\html-gateway\ui\BUILD\node_modules\rollup-plugin-progress\dist\rollup-plugi
n-progress.js:27:22)                                                                               
    at Gulp.<anonymous> (C:\www\html-gateway\ui\BUILD\gulpfile.js:199:24)                          
    at module.exports (C:\www\html-gateway\ui\BUILD\node_modules\orchestrator\lib\runTask.js:34:7) 
    at Gulp.Orchestrator._runTask (C:\www\html-gateway\ui\BUILD\node_modules\orchestrator\index.js:
273:3)                                                                                             
    at Gulp.Orchestrator._runStep (C:\www\html-gateway\ui\BUILD\node_modules\orchestrator\index.js:
214:10)                                                                                            
    at Gulp.Orchestrator.start (C:\www\html-gateway\ui\BUILD\node_modules\orchestrator\index.js:134
:8)                                                                                                
    at runNextSet (C:\www\html-gateway\ui\BUILD\node_modules\run-sequence\index.js:86:16)          
    at runSequence (C:\www\html-gateway\ui\BUILD\node_modules\run-sequence\index.js:97:2)          
    at C:\www\html-gateway\ui\BUILD\gulpfile.js:772:9                                              
````

I have been using all my gulp modules with [run-sequence](https://www.npmjs.com/package/run-sequence) for some years now,

**Comment by jkuri** [comment]
please try now (0.4.0).
